---

- include: dependencies.yml
- include: mounts.yml

- name: Stop and disable zookeeper in slave nodes
  service:
    name: zookeeper
    enabled: no
    state: stopped
  tags:
    - zookeeper

- name: Stop and disable mesos-master in slave nodes
  service:
    name: mesos-master
    enabled: no
    state: stopped
  tags:
    - mesos

- name: Configure zookeeper addresses to mesos-slave
  template:
    src: zk.j2
    dest: /etc/mesos/zk
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mesos-slave
  tags:
    - mesos

- name: Setup hostname for mesos-slave
  copy:
    content: "{{ inventory_hostname }}"
    dest: /etc/mesos-slave/hostname
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mesos-slave
  tags:
    - mesos

- name: Setup containerizers for mesos-slave
  copy:
    content: "{{ containerizers }}"
    dest: /etc/mesos-slave/containerizers
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mesos-slave
  tags:
    - mesos

- name: Setup attributes for mesos-slave
  template:
    src: attributes.j2
    dest: /etc/mesos-slave/attributes
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mesos-slave
  tags:
    - mesos

- name: Setup resources for mesos-slave
  copy:
    content: "{{ resources }}"
    dest: /etc/mesos-slave/resources
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mesos-slave
  tags:
    - mesos

- name: Setup container timeout for mesos-slave
  copy:
    content: "{{ container_timeout }}"
    dest: /etc/mesos-slave/executor_registration_timeout
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mesos-slave
  tags:
    - mesos

- name: Periodically delete stopped docker containers
  cron:
    name: 'Remove stopped containers'
    special_time: 'daily'
    job: 'docker ps -aq --no-trunc -f status=exited | xargs docker rm'
    user: 'root'
  tags:
    - docker

- name: Periodically delete dangling docker images
  cron:
    name: 'Remove dangling images'
    special_time: 'daily'
    job: 'docker images -q -f dangling=true | xargs docker rmi'
    user: 'root'
  tags:
    - docker

- name: Setup consul service and check definitions
  template:
    src: consul.json.j2
    dest: /etc/consul.d/mesos-slave.json
    owner: root
    group: root
    mode: 0644
  notify:
    - restart consul
  tags:
    - consul
